# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f62c1c17da446166a84ec356530b603a626c7ffd69ba44cc091bc33afc0a16be72c90847e39556be16a9b60f3171995ea4360e36be63af11b87b2aa064343d

test:
  secret_key_base: b2b0f06c85424c24e2a3d5aa42a717fdc88ec8982846f4768b1952cb5ed942cdb41f99cb94136e17e64cc49284572d0b3af8a7ff130f189c2b7b53905d6bdcf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
